# Generated by Django 5.2.8 on 2025-11-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('grado_cargo', models.CharField(max_length=50)),
                ('antiguedad', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
